# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-04-27 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flickr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavouritePhoto',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('farm', models.IntegerField()),
                ('server', models.CharField(max_length=255)),
                ('secret', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ('name',)},
        ),
    ]
