# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-04-27 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flickr', '0002_auto_20200427_0805'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favouritephoto',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='favouritephoto',
            name='title',
            field=models.CharField(blank=True, max_length=2047, null=True),
        ),
    ]
