# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-04-27 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('flickr', '0003_auto_20200427_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='favouritephoto',
            name='uid',
            field=models.CharField(max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='favouritephoto',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
