# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-04-27 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flickr', '0004_auto_20200427_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favouritephoto',
            name='uid',
            field=models.CharField(max_length=255, unique=True, verbose_name='UID'),
        ),
    ]
